name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_state_notifier: ^1.0.0
  provider: ^6.0.0
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

dependency_overrides:
  flutter_state_notifier:
    path: ../packages/flutter_state_notifier
  state_notifier:
    path: ../packages/state_notifier

flutter:
  uses-material-design: true