name: state_notifier
description: ValueNotifier, but outside Flutter and with some extra perks
version: 1.0.0
homepage: https://github.com/rrousselGit/state_notifier

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  mockito: ^5.0.15
  test: ^1.12.0
