name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_state_notifier: ^1.0.0
  provider: ^6.0.0
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

dependency_overrides:
  flutter_state_notifier:
    path: ../../flutter_state_notifier
  state_notifier:
    path: ../

flutter:
  uses-material-design: true